-- MySQL Script generated by MySQL Workbench
-- Sat May 11 16:04:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cool_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cool_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cool_shop` DEFAULT CHARACTER SET utf8 ;
USE `cool_shop` ;

-- -----------------------------------------------------
-- Table `cool_shop`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `middlename` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_hash_UNIQUE` (`password_hash` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`stores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`currencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `currency_name_UNIQUE` (`currency_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `language_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `currecy_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_id_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_currency_id_idx` (`currecy_id` ASC) VISIBLE,
  INDEX `fk_language_id_idx` (`language_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_country_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `cool_shop`.`stores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_country_currency_id`
    FOREIGN KEY (`currecy_id`)
    REFERENCES `cool_shop`.`currencies` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_country_language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `cool_shop`.`languages` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`customer_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`customer_addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  `postcode` VARCHAR(6) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_country_id_idx` (`country_id` ASC) VISIBLE,
  INDEX `fk_customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_address_country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `cool_shop`.`countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_address_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cool_shop`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_hash_UNIQUE` (`password_hash` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `child_count` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `sku` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`m2m_category_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`m2m_category_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_m2m_category_product_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `cool_shop`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_m2m_category_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `cool_shop`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`attribute_templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`attribute_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`attribute_sets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`attribute_sets` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `language_id` INT NOT NULL,
  `attribute_template_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_language_id_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_attribute_template_id_idx` (`attribute_template_id` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_set_language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `cool_shop`.`languages` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_attribute_set_attribute_template_id`
    FOREIGN KEY (`attribute_template_id`)
    REFERENCES `cool_shop`.`attribute_templates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`attributes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attribute_set_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_set_id_idx` (`attribute_set_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_attribute_set_id`
    FOREIGN KEY (`attribute_set_id`)
    REFERENCES `cool_shop`.`attribute_sets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attribute_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `cool_shop`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`product_gallery_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`product_gallery_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`product_galleries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`product_galleries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `product_gallery_type_id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_product_gallery_type_id_idx` (`product_gallery_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_gallery_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `cool_shop`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_gallery_product_gallery_type_id`
    FOREIGN KEY (`product_gallery_type_id`)
    REFERENCES `cool_shop`.`product_gallery_types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`m2m_customer_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`m2m_customer_product` (
  `id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_m2m_customer_product_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cool_shop`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_m2m_customer_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `cool_shop`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`m2m_store_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`m2m_store_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_id_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_m2m_store_category_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `cool_shop`.`stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_m2m_store_category_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `cool_shop`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`m2m_store_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`m2m_store_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_id_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_m2m_store_product_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `cool_shop`.`stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_m2m_store_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `cool_shop`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`product_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`product_prices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `value` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_currency_id_idx` (`currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_price_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `cool_shop`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_price_currency_id`
    FOREIGN KEY (`currency_id`)
    REFERENCES `cool_shop`.`currencies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`page_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`page_contents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `value` TEXT NULL,
  `language_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_language_id_idx` (`language_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_page_content_language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `cool_shop`.`languages` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`configs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`configs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `sum` DECIMAL(7,2) NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cool_shop`.`customers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`m2m_order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`m2m_order_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_m2m_order_product_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `cool_shop`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_m2m_order_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `cool_shop`.`products` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_shop`.`m2m_category_attribute_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_shop`.`m2m_category_attribute_set` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `attribute_set_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_attribute_set_id_idx` (`attribute_set_id` ASC) VISIBLE,
  CONSTRAINT `fk_m2m_category_attribute_set_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `cool_shop`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_m2m_category_attribute_set_attribute_set_id`
    FOREIGN KEY (`attribute_set_id`)
    REFERENCES `cool_shop`.`attribute_sets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
